# Generated by Django 6.0 on 2025-12-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-fecha_publicacion']},
        ),
        migrations.RemoveField(
            model_name='cat',
            name='id',
        ),
        migrations.AddField(
            model_name='cat',
            name='categoria_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='cat',
            name='descripcion',
            field=models.TextField(default='Sin datos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noticia',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, default='static/post_default.png', null=True, upload_to='media'),
        ),
    ]
